### ISSUE TITLE
Only playing against the same 2 bots

### ISSUE THREAD

**Issue by melsonius** [riddlesio/issues#3]
For the last almost 2 days, my bot has only played random games against two different bots.  There were a few times where someone challenged me, but the regularly scheduled matches are only against BeetleBorg and Honneamise.

**Comment by melsonius** [comment]
On a related note, I don't think the rating/points are being updated, either.

**Comment by Honneamise** [comment]
Hello , Honneamise here :-)

I have noticed the same and i also noticed that :

according to leaderboard player 2 ( UYoP ) with 1358 points have NO MATCH PLAYED AT ALL !!!

**Comment by siberianice** [comment]
Hi! Me too) No play for two days. siberianice_bot.

**Comment by nikovanmeurs** [comment]
Being matched against 2 bots is actually by design. It allowed us to have a relatively simple scheduling implementation was good enough until we had the time and resources to do it right (ie. the user experience being good enough across the board). 

Having said that. we're finally at the point where we can start working on incremental improvements. I'm actually reworking the match scheduling algorithm this week. You can expect more varied matchups either before Thursday or somewhere next week (I'm out of office this Thu/Fri).

Regarding the rating: it's certainly being updated. There were no bots in the 1400s before the weekend.

**Comment by Elirso** [comment]
Would it be possible at least to be matched against the bot right above and right under you ? because right now i'm matched against the same bots and the matches last 10 rounds...

Also for some reason I can't challenge the 1st bot, and I have never played a game against him. That's pretty frustrating.

**Comment by nikovanmeurs** [comment]
We deployed the new scheduling algorithm just now.

Everyone should now get a match every hour, as long as your opponent does not disable his/her bot between the time the match is scheduled and the match is to be played.

You have a 90% chance to be scheduled against the 3 bots above and the 3 bots below your rank and 10% chance that you're scheduled against any other bot.

**Comment by melsonius** [comment]
Looks like it's working better now. Thanks!
